name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER: `$TITLE` by @$AUTHOR'
sort-direction: ascending
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '⚒️ Breaking Changes'
    labels:
      - 'breaking-change'

  - title: '📋 Documentation'
    labels:
      - 'documentation'

  - title: '🚀 Features'
    labels:
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'bug-fix'
      - 'bug'

  - title: '🧰 Maintenance'
    label: 'patch'

  - title: '📦 Dependencies'
    labels:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Say thanks

  [![Sponsor Buy Me a Coffee](https://img.shields.io/badge/Sponsor-Buy_Me_a_Coffee-yellow?style=for-the-badge)](https://buymeacoffee.com/UnoSite)
  [![Sponsor PayPal.Me](https://img.shields.io/badge/Sponsor-PayPal.me-blue?style=for-the-badge)](https://paypal.me/UnoSite)
