name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER: `$TITLE` by @$AUTHOR'
sort-direction: ascending
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '⚒️ Breaking Changes'
    labels:
      - 'breaking-change'

  - title: '📋 Documentation'
    labels:
      - 'documentation'

  - title: '🚀 Features'
    labels:
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'bug-fix'
      - 'bug'

  - title: '🧰 Maintenance'
    label: 'patch'

  - title: '📦 Dependencies'
    labels:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Say thanks

  [![Sponsor Github](https://img.shields.io/badge/Sponsor-Github-EA4AAA?style=for-the-badge&logo=githubsponsors)](https://github.com/sponsors/UnoSite)\
  [![Sponsor Buy Me a Coffee](https://img.shields.io/badge/Sponsor-By%20me%20a%20coffee-FFDD00?style=for-the-badge&logo=buymeacoffee)](https://buymeacoffee.com/UnoSite)\
  [![Sponsor PayPal.Me](https://img.shields.io/badge/Sponsor-paypal.me-003087?style=for-the-badge&logo=paypal)](https://paypal.me/UnoSite)
