project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /custom_components/isitpayday/translations/en.json
    translation: /custom_components/isitpayday/translations/%two_letters_code%.json
