name: Release
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  COMPONENT_DIR: isitpayday

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update manifest.json version to ${{ github.event.release.tag_name }}
        run: |
          python .github/scripts/update_hacs_manifest.py --version ${{ github.event.release.tag_name }} --path /custom_components/isitpayday/
      - name: Commit manifest update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@github.com'
          git add custom_components/isitpayday/manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "Updated manifest.json"
            git push
          fi
      - name: Create zip
        run: |
          cd custom_components/isitpayday
          zip isitpayday.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file: ./custom_components/isitpayday/isitpayday.zip
          asset_name: isitpayday.zip
          tag: ${{ github.ref }}
          overwrite: true
