name: Request PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  request_review:
    runs-on: ubuntu-latest
    steps:
      - name: Request a review
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          reviewers: '["UnoSite"]'
