name: Request PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  PR_REVIEWERS: '["UnoSite"]'

jobs:
  request_review:
    runs-on: ubuntu-latest
    steps:
      - name: Sæt miljøvariabel for reviewers
        run: echo "PR_REVIEWERS_JSON=${{ env.PR_REVIEWERS }}" >> $GITHUB_ENV

      - name: Anmod om et review
        if: ${{ !contains(fromJSON(env.PR_REVIEWERS_JSON), github.actor) }}
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          reviewers: ${{ env.PR_REVIEWERS }}
